#pragma once

namespace ata
{
    enum CommandE
    {
        Command_NOP = 0x00,
        Command_CFA_REQUEST_EXTENDED_ERROR_CODE = 0x03,
        Command_DATA_SET_MANAGEMENT = 0x06,
        Command_DATA_SET_MANAGEMENT_XL = 0x07,
        Command_REQUEST_SENSE_DATA_EXT = 0x0B,
        Command_GET_PHYSICAL_ELEMENT_STATUS = 0x12,
        Command_READ_SECTORS = 0x20,
        Command_READ_SECTORS_EXT = 0x24,
        Command_READ_DMA_EXT = 0x25,
        Command_READ_STREAM_DMA_EXT = 0x2A,
        Command_READ_STREAM_EXT = 0x2B,
        Command_READ_LOG_EXT = 0x2F,
        Command_WRITE_SECTORS = 0x30,
        Command_WRITE_SECTORS_EXT = 0x34,
        Command_WRITE_DMA_EXT = 0x35,
        Command_CFA_WRITE_SECTORS_WITHOUT_ERASE = 0x38,
        Command_WRITE_STREAM_DMA_EXT = 0x3A,
        Command_WRITE_STREAM_EXT = 0x3B,
        Command_WRITE_DMA_FUA_EXT = 0x3D,
        Command_WRITE_LOG_EXT = 0x3F,
        Command_READ_VERIFY_SECTORS = 0x40,
        Command_READ_VERIFY_SECTORS_EXT = 0x42,
        Command_ZERO_EXT = 0x44,
        Command_WRITE_UNCORRECTABLE_EXT = 0x45,
        Command_READ_LOG_DMA_EXT = 0x47,
        Command_ZAC_MANAGEMENT_IN = 0x4A,
        Command_CONFIGURE_STREAM = 0x51,
        Command_WRITE_LOG_DMA_EXT = 0x57,
        Command_TRUSTED_NON_DATA = 0x5B,
        Command_TRUSTED_RECEIVE = 0x5C,
        Command_TRUSTED_RECEIVE_DMA = 0x5D,
        Command_TRUSTED_SEND = 0x5E,
        Command_TRUSTED_SEND_DMA = 0x5F,
        Command_READ_FPDMA_QUEUED = 0x60,
        Command_WRITE_FPDMA_QUEUED = 0x61,
        Command_NCQ_NON_DATA = 0x63,
        Command_SEND_FPDMA_QUEUED = 0x64,
        Command_RECEIVE_FPDMA_QUEUED = 0x65,
        Command_SET_DATE_AND_TIME_EXT = 0x77,
        Command_ACCESSIBLE_MAX_ADDRESS_CONFIGURATION = 0x78,
        Command_REMOVE_ELEMENT_AND_TRUNCATE = 0x7C,
        Command_RESTORE_ELEMENTS_AND_REBUILD = 0x7D,
        Command_REMOVE_ELEMENT_AND_MODIFY_ZONES = 0x7E,
        Command_CFA_TRANSLATE_SECTOR = 0x87,
        Command_EXECUTE_DEVICE_DIAGNOSTIC = 0x90,
        Command_DOWNLOAD_MICROCODE = 0x92,
        Command_DOWNLOAD_MICROCODE_DMA = 0x93,
        Command_MUTATE_EXT = 0x96,
        Command_ZAC_MANAGEMENT_OUT = 0x9F,
        Command_PACKET = 0xA0,
        Command_SMART = 0xB0,
        Command_SET_SECTOR_CONFIGURATION_EXT = 0xB2,
        Command_SANITIZE_DEVICE = 0xB4,
        Command_READ_DMA = 0xC8,
        Command_WRITE_DMA = 0xCA,
        Command_CFA_WRITE_MULTIPLE_WITHOUT_ERASE = 0xCD,
        Command_STANDBY_IMMEDIATE = 0xE0,
        Command_IDLE_IMMEDIATE = 0xE1,
        Command_STANDBY = 0xE2,
        Command_IDLE = 0xE3,
        Command_READ_BUFFER = 0xE4,
        Command_CHECK_POWER_MODE = 0xE5,
        Command_SLEEP = 0xE6,
        Command_FLUSH_CACHE = 0xE7,
        Command_WRITE_BUFFER = 0xE8,
        Command_READ_BUFFER_DMA = 0xE9,
        Command_FLUSH_CACHE_EXT = 0xEA,
        Command_WRITE_BUFFER_DMA = 0xEB,
        Command_IDENTIFY_DEVICE = 0xEC,
        Command_SET_FEATURES = 0xEF,
        Command_SECURITY_SET_PASSWORD = 0xF1,
        Command_SECURITY_UNLOCK = 0xF2,
        Command_SECURITY_ERASE_PREPARE = 0xF3,
        Command_SECURITY_ERASE_UNIT = 0xF4,
        Command_SECURITY_FREEZE_LOCK = 0xF5,
        Command_DISABLE_PASSWORD = 0xF6,
    };
}
